var greeting = 'how are you';
console.log(greeting)
var greeting = "how are you";
console.log(greeting);
var greeting = "how are you";
console.log(greeting);
var greeting = "how are you";
console.log(greeting);
var greeting = "how are you";
console.log(greeting);
var greeting = "how are you";
console.log(greeting);
var greeting = "how are you";
console.log(greeting);
var greeting = "how are you";
console.log(greeting);
var greeting = "how are you";
console.log(greeting);
var greeting = "how are you";
console.log(greeting);